package com.clinicaltrial.ddd.trial.application.service;

import com.clinicaltrial.ddd.common.infrastructure.EventBus;
import com.clinicaltrial.ddd.common.model.BusinessRuleViolationException;
import com.clinicaltrial.ddd.trial.application.command.ConfigureAdverseRuleCommand;
import com.clinicaltrial.ddd.trial.domain.model.aggregate.Project;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.AdverseEventRuleId;
import com.clinicaltrial.ddd.trial.domain.repository.ProjectRepository;

/**
 * Application service for Adverse Event Rule configuration use cases.
 * <p>
 * Orchestrates the configuration of adverse event detection rules within
 * a clinical trial project. This service delegates all business logic to
 * the Project aggregate.
 * </p>
 *
 * <h3>Use Cases</h3>
 * <ul>
 *   <li>{@link #configureAdverseRule(ConfigureAdverseRuleCommand)} — Configure
 *       an adverse event detection rule for a specific stage and CRF field</li>
 * </ul>
 */
public class AdverseRuleApplicationService {

    private final ProjectRepository projectRepository;
    private final EventBus eventBus;

    /**
     * Constructs the application service with its required dependencies.
     *
     * @param projectRepository the repository for Project aggregates
     * @param eventBus          the infrastructure event bus
     */
    public AdverseRuleApplicationService(ProjectRepository projectRepository, EventBus eventBus) {
        this.projectRepository = projectRepository;
        this.eventBus = eventBus;
    }

    /**
     * Configures an adverse event detection rule.
     * <p>
     * Loads the project, delegates to {@link Project#configureAdverseRule(
     * AdverseEventRuleId, com.clinicaltrial.ddd.trial.domain.model.valueobject.StageId,
     * com.clinicaltrial.ddd.trial.domain.model.valueobject.CrfTemplateId,
     * com.clinicaltrial.ddd.trial.domain.model.valueobject.CrfVersionId,
     * com.clinicaltrial.ddd.trial.domain.model.valueobject.AdverseJudgeType,
     * String, String, String, String)}, and persists.
     * </p>
     *
     * @param command the configure-adverse-rule command
     * @return the updated project
     * @throws IllegalArgumentException         if command is null
     * @throws BusinessRuleViolationException    if business rules are violated
     */
    public Project configureAdverseRule(ConfigureAdverseRuleCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null");
        }

        // Load the project aggregate
        Project project = projectRepository.getById(command.getProjectId());

        // Delegate to the aggregate
        AdverseEventRuleId ruleId = new AdverseEventRuleId(null); // ID generated by persistence
        project.configureAdverseRule(ruleId, command.getStageId(), command.getCrfId(),
                command.getCrfVersionId(), command.getJudgeType(),
                command.getFieldCode(), command.getFieldName(),
                command.getValueCode(), command.getValueName());

        // Persist
        Project savedProject = projectRepository.save(project);

        // Publish events
        eventBus.publishAll(savedProject);

        return savedProject;
    }
}
