package com.clinicaltrial.ddd.trial.application.service;

import com.clinicaltrial.ddd.common.infrastructure.EventBus;
import com.clinicaltrial.ddd.common.model.BusinessRuleViolationException;
import com.clinicaltrial.ddd.trial.application.command.CreateCrfTemplateCommand;
import com.clinicaltrial.ddd.trial.domain.model.aggregate.CrfTemplate;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.CrfTemplateId;
import com.clinicaltrial.ddd.trial.domain.repository.CrfTemplateRepository;

/**
 * Application service for CrfTemplate aggregate use cases.
 * <p>
 * Orchestrates the creation, publishing, and copying of CRF templates.
 * This service follows the DDD application service pattern: it receives
 * commands, delegates to domain objects for business logic, persists via
 * the repository, and publishes domain events through the event bus.
 * </p>
 *
 * <h3>Use Cases</h3>
 * <ul>
 *   <li>{@link #createTemplate(CreateCrfTemplateCommand)} — Create a new template</li>
 *   <li>{@link #publishTemplate(CrfTemplateId)} — Publish a DRAFT template</li>
 *   <li>{@link #copyTemplate(CrfTemplateId, String)} — Deep-copy a template</li>
 * </ul>
 */
public class CrfTemplateApplicationService {

    private final CrfTemplateRepository crfTemplateRepository;
    private final EventBus eventBus;

    /**
     * Constructs the application service with its required dependencies.
     *
     * @param crfTemplateRepository the repository for CrfTemplate aggregates
     * @param eventBus              the infrastructure event bus
     */
    public CrfTemplateApplicationService(CrfTemplateRepository crfTemplateRepository,
                                          EventBus eventBus) {
        this.crfTemplateRepository = crfTemplateRepository;
        this.eventBus = eventBus;
    }

    /**
     * Creates a new CRF template in DRAFT status.
     * <p>
     * Creates the CrfTemplate aggregate, persists it, and publishes the
     * {@link com.clinicaltrial.ddd.trial.domain.event.CrfTemplateCreatedEvent}.
     * </p>
     *
     * @param command the create-template command
     * @return the created template
     * @throws IllegalArgumentException         if command is null
     * @throws BusinessRuleViolationException    if business rules are violated
     */
    public CrfTemplate createTemplate(CreateCrfTemplateCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null");
        }

        // Create the aggregate
        CrfTemplateId templateId = new CrfTemplateId(null); // ID generated by persistence
        CrfTemplate template = CrfTemplate.create(
                templateId,
                command.getName(),
                null, // defaultVersionId
                command.getCode(),
                command.getCategory(),
                command.getEstimateTime(),
                command.getNotice(),
                command.getIntroduce());

        // Persist
        CrfTemplate savedTemplate = crfTemplateRepository.save(template);

        // Publish events
        eventBus.publishAll(savedTemplate);

        return savedTemplate;
    }

    /**
     * Publishes a CRF template, transitioning it from DRAFT to PUBLISHED status.
     * <p>
     * Loads the template, calls the domain {@link CrfTemplate#publish()} method,
     * persists the change.
     * </p>
     *
     * @param templateId the identity of the template to publish
     * @return the published template
     * @throws BusinessRuleViolationException if the template cannot be published
     */
    public CrfTemplate publishTemplate(CrfTemplateId templateId) {
        if (templateId == null) {
            throw new IllegalArgumentException("templateId must not be null");
        }

        CrfTemplate template = crfTemplateRepository.getById(templateId);
        template.publish();

        CrfTemplate savedTemplate = crfTemplateRepository.save(template);
        eventBus.publishAll(savedTemplate);

        return savedTemplate;
    }

    /**
     * Creates a deep copy of a CRF template with a new name.
     * <p>
     * Loads the source template, delegates to {@link CrfTemplate#copy(String)},
     * persists the new template, and publishes events from the new template.
     * </p>
     *
     * @param templateId the identity of the template to copy
     * @param newName    the name for the new template
     * @return the newly created copy
     * @throws BusinessRuleViolationException if the template cannot be copied
     */
    public CrfTemplate copyTemplate(CrfTemplateId templateId, String newName) {
        if (templateId == null) {
            throw new IllegalArgumentException("templateId must not be null");
        }
        if (newName == null || newName.trim().isEmpty()) {
            throw new IllegalArgumentException("newName must not be blank");
        }

        CrfTemplate sourceTemplate = crfTemplateRepository.getById(templateId);

        CrfTemplate copiedTemplate = sourceTemplate.copy(newName.trim());

        // Persist the new template
        CrfTemplate savedTemplate = crfTemplateRepository.save(copiedTemplate);

        // Publish events from the new template (includes CrfTemplateCreatedEvent)
        eventBus.publishAll(savedTemplate);

        return savedTemplate;
    }
}
