package com.clinicaltrial.ddd.trial.application.service;

import org.springframework.stereotype.Service;
import com.clinicaltrial.ddd.common.infrastructure.EventBus;
import com.clinicaltrial.ddd.common.model.BusinessRuleViolationException;
import com.clinicaltrial.ddd.trial.application.command.CreateProjectCommand;
import com.clinicaltrial.ddd.trial.domain.model.aggregate.Project;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.ProjectId;
import com.clinicaltrial.ddd.trial.domain.repository.ProjectRepository;
import com.clinicaltrial.ddd.trial.domain.service.ProjectDomainService;

import java.util.UUID;

/**
 * Application service for Project aggregate use cases.
 * <p>
 * Orchestrates the creation and state transition of clinical trial projects.
 * This service follows the DDD application service pattern: it receives
 * commands, delegates to domain objects for business logic, persists via
 * the repository, and publishes domain events through the event bus.
 * </p>
 *
 * <h3>Use Cases</h3>
 * <ul>
 *   <li>{@link #createProject(CreateProjectCommand)} — Create a new project in DRAFT status</li>
 *   <li>{@link #activateProject(ProjectId)} — Activate a DRAFT project</li>
 *   <li>{@link #closeProject(ProjectId)} — Close an ACTIVE project</li>
 * </ul>
 */
@Service
public class ProjectApplicationService {

    private final ProjectRepository projectRepository;
    private final ProjectDomainService projectDomainService;
    private final EventBus eventBus;

    /**
     * Constructs the application service with its required dependencies.
     *
     * @param projectRepository    the repository for Project aggregates
     * @param projectDomainService the domain service for project validations
     * @param eventBus             the infrastructure event bus
     */
    public ProjectApplicationService(ProjectRepository projectRepository,
                                      ProjectDomainService projectDomainService,
                                      EventBus eventBus) {
        this.projectRepository = projectRepository;
        this.projectDomainService = projectDomainService;
        this.eventBus = eventBus;
    }

    /**
     * Creates a new clinical trial project.
     * <p>
     * Validates dates and prefix uniqueness, creates the Project aggregate
     * in DRAFT status, persists it, and publishes the
     * {@link com.clinicaltrial.ddd.trial.domain.event.ProjectCreatedEvent}.
     * </p>
     *
     * @param command the creation command
     * @return the created project
     * @throws IllegalArgumentException         if command is null
     * @throws BusinessRuleViolationException    if business rules are violated
     */
    public Project createProject(CreateProjectCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null");
        }

        // Domain validations
        projectDomainService.validateProjectDates(
                command.getExpectStartAt(), command.getExpectEndAt());
        projectDomainService.validatePrefixUniqueness(command.getPrefix());

        // Create the aggregate
        ProjectId projectId = new ProjectId(null); // ID will be generated by persistence
        Project project = Project.create(
                projectId,
                command.getTitle(),
                command.getType(),
                command.getAbbreviation(),
                command.getPrefix(),
                command.isOpenScreen(),
                command.getExpectedSubjectSize(),
                command.getClinicalNumber(),
                command.getRegistrationNo(),
                command.getExpectStartAt(),
                command.getExpectEndAt(),
                command.getPurpose(),
                command.getCreateUserId());

        // Persist
        Project savedProject = projectRepository.save(project);

        // Publish events
        eventBus.publishAll(savedProject);

        return savedProject;
    }

    /**
     * Activates a project, transitioning it from DRAFT to ACTIVE status.
     * <p>
     * Loads the project, calls the domain {@link Project#activate()} method,
     * persists the change, and publishes the
     * {@link com.clinicaltrial.ddd.trial.domain.event.ProjectActivatedEvent}.
     * </p>
     *
     * @param projectId the identity of the project to activate
     * @return the activated project
     * @throws BusinessRuleViolationException if the project cannot be activated
     */
    public Project activateProject(ProjectId projectId) {
        if (projectId == null) {
            throw new IllegalArgumentException("projectId must not be null");
        }

        Project project = projectRepository.getById(projectId);
        project.activate();

        Project savedProject = projectRepository.save(project);
        eventBus.publishAll(savedProject);

        return savedProject;
    }

    /**
     * Closes a project, transitioning it from ACTIVE to CLOSED status.
     * <p>
     * Loads the project, calls the domain {@link Project#close()} method,
     * persists the change.
     * </p>
     *
     * @param projectId the identity of the project to close
     * @return the closed project
     * @throws BusinessRuleViolationException if the project cannot be closed
     */
    public Project closeProject(ProjectId projectId) {
        if (projectId == null) {
            throw new IllegalArgumentException("projectId must not be null");
        }

        Project project = projectRepository.getById(projectId);
        project.close();

        Project savedProject = projectRepository.save(project);
        eventBus.publishAll(savedProject);

        return savedProject;
    }
}
