package com.clinicaltrial.ddd.trial.application.service;

import org.springframework.stereotype.Service;
import com.clinicaltrial.ddd.common.infrastructure.EventBus;
import com.clinicaltrial.ddd.common.model.BusinessRuleViolationException;
import com.clinicaltrial.ddd.trial.application.command.AssignSitePersonnelCommand;
import com.clinicaltrial.ddd.trial.domain.model.aggregate.Project;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.SitePersonnelId;
import com.clinicaltrial.ddd.trial.domain.repository.ProjectRepository;

/**
 * Application service for Site Personnel management use cases.
 * <p>
 * Orchestrates the assignment of personnel to trial sites. This service
 * delegates all business logic to the Project aggregate.
 * </p>
 *
 * <h3>Use Cases</h3>
 * <ul>
 *   <li>{@link #assignPersonnel(AssignSitePersonnelCommand)} — Assign a user
 *       to a trial site with a specific role</li>
 * </ul>
 */
@Service
public class SitePersonnelApplicationService {

    private final ProjectRepository projectRepository;
    private final EventBus eventBus;

    /**
     * Constructs the application service with its required dependencies.
     *
     * @param projectRepository the repository for Project aggregates
     * @param eventBus          the infrastructure event bus
     */
    public SitePersonnelApplicationService(ProjectRepository projectRepository, EventBus eventBus) {
        this.projectRepository = projectRepository;
        this.eventBus = eventBus;
    }

    /**
     * Assigns personnel to a trial site.
     * <p>
     * Loads the project, delegates to {@link Project#assignPersonnel(
     * SitePersonnelId, Long, Long,
     * com.clinicaltrial.ddd.trial.domain.model.valueobject.SiteRole)},
     * and persists.
     * </p>
     *
     * @param command the assign-personnel command
     * @return the updated project
     * @throws IllegalArgumentException         if command is null
     * @throws BusinessRuleViolationException    if business rules are violated
     */
    public Project assignPersonnel(AssignSitePersonnelCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null");
        }

        // Load the project aggregate
        Project project = projectRepository.getById(command.getProjectId());

        // Delegate to the aggregate
        SitePersonnelId personnelId = new SitePersonnelId(null); // ID generated by persistence
        project.assignPersonnel(personnelId, command.getUserId(),
                command.getSiteId(), command.getRole());

        // Persist
        Project savedProject = projectRepository.save(project);

        // Publish events
        eventBus.publishAll(savedProject);

        return savedProject;
    }
}
