package com.clinicaltrial.ddd.trial.application.service;

import org.springframework.stereotype.Service;
import com.clinicaltrial.ddd.common.infrastructure.EventBus;
import com.clinicaltrial.ddd.common.model.BusinessRuleViolationException;
import com.clinicaltrial.ddd.trial.application.command.AddStageCommand;
import com.clinicaltrial.ddd.trial.domain.model.aggregate.Project;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.BaselineInterval;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.ProjectId;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.StageId;
import com.clinicaltrial.ddd.trial.domain.model.valueobject.WindowPeriod;
import com.clinicaltrial.ddd.trial.domain.repository.ProjectRepository;

/**
 * Application service for Stage management use cases.
 * <p>
 * Orchestrates the addition and removal of stages within a clinical trial
 * project. This service delegates all business logic to the Project aggregate.
 * </p>
 *
 * <h3>Use Cases</h3>
 * <ul>
 *   <li>{@link #addStage(AddStageCommand)} — Add a new stage to a project</li>
 * </ul>
 */
@Service
public class StageApplicationService {

    private final ProjectRepository projectRepository;
    private final EventBus eventBus;

    /**
     * Constructs the application service with its required dependencies.
     *
     * @param projectRepository the repository for Project aggregates
     * @param eventBus          the infrastructure event bus
     */
    public StageApplicationService(ProjectRepository projectRepository, EventBus eventBus) {
        this.projectRepository = projectRepository;
        this.eventBus = eventBus;
    }

    /**
     * Adds a new stage to the project.
     * <p>
     * Loads the project, delegates to {@link Project#addStage(StageId, String,
     * com.clinicaltrial.ddd.trial.domain.model.valueobject.StageRepeatType, boolean,
     * BaselineInterval, WindowPeriod, String)}, persists, and publishes events.
     * </p>
     *
     * @param command the add-stage command
     * @return the updated project
     * @throws IllegalArgumentException         if command is null
     * @throws BusinessRuleViolationException    if business rules are violated
     */
    public Project addStage(AddStageCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null");
        }

        // Load the project aggregate
        Project project = projectRepository.getById(command.getProjectId());

        // Build value objects from command data
        BaselineInterval baselineInterval = null;
        if (command.getBaselineInterval() != null && command.getBaselineIntervalUnit() != null) {
            baselineInterval = new BaselineInterval(
                    command.getBaselineInterval(), command.getBaselineIntervalUnit());
        }

        WindowPeriod windowPeriod = null;
        if (command.getWindowBeforeDays() != null || command.getWindowAfterDays() != null) {
            windowPeriod = new WindowPeriod(
                    command.getWindowBeforeDays() != null ? command.getWindowBeforeDays() : 0L,
                    command.getWindowAfterDays() != null ? command.getWindowAfterDays() : 0L);
        }

        // Delegate to the aggregate
        StageId stageId = new StageId(null); // ID will be generated by persistence
        project.addStage(stageId, command.getName(), command.getRepeatType(),
                command.isAutoAdd(), baselineInterval, windowPeriod, null);

        // Persist
        Project savedProject = projectRepository.save(project);

        // Publish events
        eventBus.publishAll(savedProject);

        return savedProject;
    }
}
