package com.clinicaltrial.ddd.subject.domain.model.valueobject;

import com.clinicaltrial.ddd.common.model.ValueObject;

import java.util.Objects;

/**
 * Value Object representing the unique identity of a Subject aggregate.
 * <p>
 * Wraps a {@link Long} identifier that is assigned by the persistence layer or
 * generated by a sequence. Instances are immutable and compared by their wrapped value.
 * </p>
 */
public class SubjectId implements ValueObject {

    private final Long value;

    /**
     * Creates a new SubjectId.
     *
     * @param value the raw identifier; must not be null
     * @throws IllegalArgumentException if value is null
     */
    public SubjectId(Long value) {
        if (value == null) {
            throw new IllegalArgumentException("SubjectId value must not be null");
        }
        this.value = value;
    }

    /**
     * Returns the raw identifier value.
     *
     * @return the wrapped Long value
     */
    public Long getValue() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubjectId subjectId = (SubjectId) o;
        return Objects.equals(value, subjectId.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return "SubjectId{" + "value=" + value + '}';
    }
}
